import { EXCEL_SANDBOX_LIMITS } from "../contracts";

export const EXCEL_SANDBOX_MAX_SAMPLE_ITEMS = 100;
export const EXCEL_SANDBOX_DEFAULT_ROW_LIMIT = 100;
export const EXCEL_SANDBOX_DEFAULT_COLUMN_LIMIT = 100;
export const EXCEL_SANDBOX_PREVIEW_ROW_LIMIT = 40;
export const EXCEL_SANDBOX_PREVIEW_COLUMN_LIMIT = 30;
export const EXCEL_SANDBOX_RESULT_PREVIEW_LIMIT = 100;
export const EXCEL_SANDBOX_MAX_FILE_SIZE_BYTES = EXCEL_SANDBOX_LIMITS.maxFileBytes;
export const EXCEL_SANDBOX_MAX_TOTAL_UPLOAD_BYTES = EXCEL_SANDBOX_LIMITS.maxTotalBytes;
export const EXCEL_SANDBOX_MAX_UPLOAD_FILES = EXCEL_SANDBOX_LIMITS.maxFiles;
export const EXCEL_SANDBOX_ALLOWED_EXTENSIONS = EXCEL_SANDBOX_LIMITS.allowedExtensions;
